apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment-02-env
data:
  envValue: "environmentSnake2"
  CONFIG_PATH: "/etc/config"
  SERVER_PORT: "8081"
  SERVER_HOST: "0.0.0.0"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment-02-config
data:
  configValue: "snake"

---

apiVersion: v1
kind: Secret
metadata:
  name: assignment-02-secret
type: Opaque
data:
  .secretValue: c2VjcmV0U25ha2U= 

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: assignment-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment-02-server
  template:
    metadata:
      labels:
        app: assignment-02-server
    spec:
      containers:
      - name: assignment-02-server
        image: uyahya/assignments:server_test
        envFrom:
          - configMapRef:
              name: assignment-02-env
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
            readOnly: true        
      volumes:
        - name: config-volume
          projected:
            sources:
              - configMap:
                  name: assignment-02-config
              - secret:
                  name: assignment-02-secret
---

apiVersion: v1
kind: Service
metadata:
  name: assignment-02-service
spec:
  type: NodePort
  selector:
    app: assignment-02-server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001